Issue 1112 - Implement Database Backup Rentention > 35 days
CSPS-EFPC-IT/generic-shell-scripts pull request #15
Opened 2023-02-11 01:49 UTC by PatrickMessierGoC

2023-02-13 15:24 UTC, FrancisMawn requested changes

2023-02-13 15:24 UTC, FrancisMawn commented on Windows/backup_database.ps1
> +# Get Input
Le nom du dossier devrait être en minuscule comme les deux autres dossiers pour ubuntu.

2023-02-13 15:24 UTC, FrancisMawn commented on Windows/backup_database.ps1
> +function Echo-Input-Parameters{
Manque un espace avant ton accolade.

2023-02-13 15:24 UTC, FrancisMawn commented on Windows/backup_database.ps1
> +    $backupRootDirectoryPath,
Je sais pas si tu as lu ce [guide](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-7.3
), mais il semblerait que les noms de paramètres devraient être nommé en pascal case.

2023-02-13 15:24 UTC, FrancisMawn commented on Windows/backup_database.ps1
> +    if(-Not(Test-Path -Path "${backupRootDirectoryPath}" -PathType Container)){
Manque un espace apres ton if. Ces erreurs sont un peu partout dans ton fichier.

Il devrait y avoir un espace avant les accolades aussi.

`if (...) {`

2023-02-13 15:24 UTC, FrancisMawn commented on Windows/backup_database.ps1
> +            Start-Process "C:\Program Files\MySQL\MySQL Workbench 8.0\mysqldump.exe" `
Le path vers le executable pourrait être un constante. Plus facile à maintenir. Même chose pour Postgres.

2023-02-13 15:24 UTC, FrancisMawn commented on Windows/backup_database.ps1
> +            # Set PGSERVICEFILE
Nécessaire?

2023-02-13 19:31 UTC, PatrickMessierGoC commented on Windows/backup_database.ps1
> +# Get Input
Fix

2023-02-13 19:32 UTC, PatrickMessierGoC commented on Windows/backup_database.ps1
> +    $backupRootDirectoryPath,
J'ai appliqué ce que me semblait pertinent.

2023-02-13 19:32 UTC, PatrickMessierGoC commented on Windows/backup_database.ps1
> +    if(-Not(Test-Path -Path "${backupRootDirectoryPath}" -PathType Container)){
J'ai formaté le code.

2023-02-13 19:32 UTC, PatrickMessierGoC commented on Windows/backup_database.ps1
> +            Start-Process "C:\Program Files\MySQL\MySQL Workbench 8.0\mysqldump.exe" `
Fait.

2023-02-13 19:32 UTC, PatrickMessierGoC commented on Windows/backup_database.ps1
> +            # Set PGSERVICEFILE
J'ai mis un commentaire plus pertinent.

2023-02-13 20:14 UTC, jlcharette approved these changes

2023-02-14 12:04 UTC, FrancisMawn approved these changes

2023-02-14 13:50 UTC, cedricguindon approved these changes

2023-02-14 18:22 UTC, PatrickMessierGoC commented on Windows/backup_database.ps1
> +function Echo-Input-Parameters{
corrigé

2023-02-14 18:23 UTC, merged